name: Docker image
on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches-ignore:
      - main
      - 'v*.*'
      - '*'

jobs:
  build:
    name: Build & push docker image
    runs-on: mend-new-runer-1-label-1
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: |
            mend-white-src-scan
            ${{ github.event.pull_request.head.ref }} 
      
      - name: Present working directory        
        run: pwd

      - name: Check PR Description for Flags
        id: check-flags
        run: |
          PR_BODY=$(jq -r .pull_request.body "$GITHUB_EVENT_PATH")
          echo "PR Body: $PR_BODY"
          if echo "$PR_BODY" | grep -q "Run Whitesource scan"; then
            echo "::set-output name=flag_a::true"
          fi
        
      - name: Get Pull Request Number
        id: pr
        run: |
          PR_NUMBER=$(gh pr view --json number -q .number)
          echo "Pull Request Number: $PR_NUMBER"
          echo "::set-output name=pull_request_number::$PR_NUMBER"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          
          
      - name: Find Whitesource Log Directory
        id: find-log-dir
        run: |
          LOG_DIR=$(ls -td /home/itadmin/mend-runner/bigfix-docker/whitesource/*/ | head -n 1)
          echo "Log directory found: $LOG_DIR"
          echo "::set-output name=log_dir::$LOG_DIR"
          
      - name: Make utility.sh Executable
        run: chmod +x /home/itadmin/mend-runner/actions-runner/_work/springboot-starterkit/springboot-starterkit/.github/utils/scripts/utility.sh
          

      - name: Run Utility Script with Whitesource Log
        run: |
          LOG_FILE="${{ steps.find-log-dir.outputs.log_dir }}whitesource.0.log"
          /home/itadmin/mend-runner/actions-runner/_work/springboot-starterkit/springboot-starterkit/.github/utils/scripts/utility.sh "$LOG_FILE"    
          
      
